# Local metrics rendering configuration
metrics:
- name: Generate Main Metrics
  with:
    filename: metrics.svg
    user: robertogogoni
    template: classic
    base: header, activity, community, repositories
    base_indepth: true
    config_timezone: America/Sao_Paulo
    repositories_forks: false
    repositories_skipped: hosts, adfilt, fuckfuckadblock, Adobe-URL-Block-List, Krakatau, developer-roadmap, awesome-oss-alternatives,
      awesome-shizuku, XClipper, apkscan, cookbook, Public-Guide, awesome-chatgpt-prompts, ubo-filters, filterlists, MoonWalker440,
      WSTxda, googlefonts-template-project, rafnixg, readme-to-markdown, chathub, datapub, github-star-graph-project, marreta,
      candle-craft-ux-vision
    plugins_errors_fatal: true
    plugin_languages: true
    plugin_languages_indepth: true
    plugin_languages_analysis_timeout: 30
    plugin_languages_analysis_timeout_repositories: 10
    plugin_languages_categories: programming
    plugin_languages_colors: github
    plugin_languages_limit: 8
    plugin_languages_sections: most-used
    plugin_languages_ignored: html, css, jupyter notebook, batchfile, makefile, adblock filter list, hcl, r
- name: Generate Isometric Calendar
  with:
    filename: metrics-isocalendar.svg
    user: robertogogoni
    template: classic
    base: ''
    config_timezone: America/Sao_Paulo
    plugin_isocalendar: true
    plugin_isocalendar_duration: full-year
- name: Generate Languages
  with:
    filename: metrics-languages.svg
    user: robertogogoni
    template: classic
    base: ''
    repositories_forks: false
    repositories_skipped: hosts, adfilt, fuckfuckadblock, Adobe-URL-Block-List, Krakatau, developer-roadmap, awesome-oss-alternatives,
      awesome-shizuku, XClipper, apkscan, cookbook, Public-Guide, awesome-chatgpt-prompts, ubo-filters, filterlists, MoonWalker440,
      WSTxda, googlefonts-template-project, rafnixg, readme-to-markdown, chathub, datapub, github-star-graph-project, marreta,
      candle-craft-ux-vision
    plugin_languages: true
    plugin_languages_indepth: true
    plugin_languages_analysis_timeout: 30
    plugin_languages_analysis_timeout_repositories: 10
    plugin_languages_limit: 10
    plugin_languages_sections: most-used
    plugin_languages_details: percentage, lines
    plugin_languages_categories: programming
    plugin_languages_ignored: html, css, jupyter notebook, batchfile, makefile, adblock filter list, hcl, r
